version: "3"
services:
  base:
    image: dash_app
    build:
      context: .
      dockerfile: Dockerfile

  app:
    depends_on:
      - base
    image: dash_app
    container_name: "dash_app_app"
    volumes:
      - .:/app
    working_dir: /app
    command: ["pipenv", "run", "python", "main.py"]

  jupyter:
    depends_on:
      - base
    image: dash_app
    container_name: "dash_app_jupyter"
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - .:/app
    working_dir: /app
    command: ["pipenv", "run", "jupyter", "lab", "--ip=0.0.0.0"]
